network:
  version: 2
  renderer: networkd
  ethernets:
    enp6s0:
      dhcp4: no
      addresses: [192.168.123.15/24]
      gateway4: 192.168.123.4
      nameservers:
        addresses: [192.168.123.4]


 
