network:
  version: 2
  renderer: networkd
  ethernets:
    enp5s0:
      dhcp4: no
    enp4s0:
      dhcp4: no

  bridges:
    br0:
      dhcp4: no
      interfaces:
        - enp5s0
        - enp4s0
      addresses: [192.168.63.15/24]

    
